services:
  app_graphql_connector:
    build:
      context: .
      dockerfile_inline: |-
        FROM ghcr.io/hasura/ndc-graphql:v0.1.3
        COPY ./ /etc/connector
    develop:
      watch:
        - path: ./
          action: sync+restart
          target: /etc/connector
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_GRAPHQL_CONNECTOR_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: $APP_GRAPHQL_CONNECTOR_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      OTEL_SERVICE_NAME: $APP_GRAPHQL_CONNECTOR_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "5681"
        protocol: tcp
