services:
  app_my_connector:
    build:
      context: .
      dockerfile: .hasura-connector/Dockerfile
    develop:
      watch:
        - path: package.json
          action: rebuild
          target: /functions/package.json
        - path: package-lock.json
          action: rebuild
          target: /functions/package-lock.json
        - path: ./
          action: sync+restart
          target: /functions
    environment:
      HASURA_SERVICE_TOKEN_SECRET: $APP_MY_CONNECTOR_HASURA_SERVICE_TOKEN_SECRET
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: $APP_MY_CONNECTOR_OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
      OTEL_SERVICE_NAME: $APP_MY_CONNECTOR_OTEL_SERVICE_NAME
    extra_hosts:
      - local.hasura.dev=host-gateway
    ports:
      - mode: ingress
        target: 8080
        published: "5764"
        protocol: tcp
